export default PICKUP = {
  LOAD: 'PICKUP-LOAD',
  REFRESH: 'PICKUP-REFRESH',
  SAVE: 'PICKUP-SAVE',
  SCHEDULE: 'PICKUP-SCHEDULE',
  AUTHORIZE: 'PICKUP-AUTHORIZE',
  SELECT_ADDRESS: 'PICKUP-SELECT-ADDRESS',
  SELECT_TIME: 'PICKUP-SELECT-TIME',
  SELECT_DATE: 'PICKUP-SELECT-DATE',
}