export default PROFILE = {
  LOAD: 'PROFILE-LOAD',
  REFRESH: 'PROFILE-REFRESH',
  SAVE: 'PROFILE-SAVE',
  EDIT_NAME: 'PROFILE-EDIT-NAME',
  EDIT_BIRTHDAY: 'PROFILE-EDIT-BIRTHDAY',
  ADD_ADDRESS: 'PROFILE-ADD-ADDRESS',
  REMOVE_ADDRESS: 'PROFILE-REMOVE-ADDRESS',
  EDIT_ADDRESS: 'PROFILE-EDIT-ADDRESS'
}